/**
 * Runs every real-instance e2e suite and reports all of their outcomes.
 *
 * Suites run sequentially even after a failure, so later suites still report
 * outcomes. The runner aggregates all selected suites before choosing its exit
 * code; a failed suite makes that exit non-zero.
 *
 * Blocked (exit 2) is reported apart from failed: it means the instance was not
 * reachable, which is an environment problem rather than a contract break.
 *
 * The SUITES list below is also the input to the per-endpoint coverage ledger
 * generated by `scripts/gen_e2e_coverage_report.mjs`: adding a suite here is what
 * makes its cases count as coverage. After adding or changing a suite, refresh
 * the ledger with `node scripts/gen_e2e_coverage_report.mjs`; the pre-commit job
 * e2e-coverage-ledger fails on a stale one. Why an endpoint is deliberately left
 * untested goes in the ledger's coverage notes, not here.
 *
 * Each suite gets FB2K_E2E_RESULTS_DIR, so its JSON summary lands in a file
 * instead of only scrolling past in the terminal (see lib/e2e-harness.mjs
 * report()). Set the variable yourself to collect a run somewhere else.
 *
 * Usage: node mcp/tests/run-e2e.mjs [suite-name ...]
 */

import { spawnSync } from "node:child_process";
import { readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const testsDir = dirname(fileURLToPath(import.meta.url));
const resultsDir = process.env.FB2K_E2E_RESULTS_DIR ?? join(testsDir, ".e2e-results");

/**
 * The suites, in order. api-surface leads because it fails fast when the runtime
 * surface disagrees with the static one, which explains any later suite that
 * cannot find its endpoints; bridge-infra follows because it covers the plumbing
 * (ports, shared state, events) that the feature suites ride on, so a break
 * there explains breaks after it; the suites that put fixture files into the
 * library come last, library-read before the ones that write to them.
 *
 * window-reload must stay the final entry: reload replaces the page document,
 * which drops every listener and buffer the earlier suites left in the page.
 *
 * This is a list rather than a directory scan: tests/ also holds three older
 * e2e-*.mjs scripts (interact, smoke, screenshot-perf) that print observations
 * without recording assertions, and one of them never exits non-zero. Sweeping
 * them in would report suites whose result means nothing.
 */
const SUITES = [
    "e2e-api-surface.mjs",
    "e2e-bridge-infra.mjs",
    "e2e-implicit-contract-snapshots.mjs",
    "e2e-metadata-multivalue.mjs",
    "e2e-lyrics-sidecar.mjs",
    "e2e-playback-queue.mjs",
    "e2e-playback-events.mjs",
    "e2e-jit-queue.mjs",
    "e2e-selection-context.mjs",
    "e2e-config-discovery.mjs",
    "e2e-audio-chain.mjs",
    "e2e-audio-viz.mjs",
    "e2e-audio-pcm.mjs",
    "e2e-audio-stream.mjs",
    "e2e-media-read.mjs",
    "e2e-file-ops.mjs",
    "e2e-window-state.mjs",
    "e2e-window-chrome.mjs",
    "e2e-window-identity.mjs",
    "e2e-window-popup.mjs",
    "e2e-playlist-events.mjs",
    "e2e-playlist-ops.mjs",
    "e2e-library-read.mjs",
    "e2e-library-albums.mjs",
    "e2e-media-write.mjs",
    "e2e-replaygain.mjs",
    "e2e-artwork-read.mjs",
    "e2e-metadata-batch.mjs",
    "e2e-window-reload.mjs",
];

function selectSuites() {
    const requested = process.argv.slice(2);
    if (requested.length > 0) {
        return requested.map((name) => (name.endsWith(".mjs") ? name : `${name}.mjs`));
    }

    // A suite added to tests/ but not to SUITES would silently never run, so the
    // gap is reported rather than left to be noticed later.
    const present = new Set(
        readdirSync(testsDir).filter(
            (name) => name.startsWith("e2e-") && name.endsWith(".mjs"),
        ),
    );
    const unlisted = [...present].filter(
        (name) => !SUITES.includes(name) && !LEGACY.includes(name),
    );
    if (unlisted.length > 0) {
        console.log(`note: not in the suite list, so not run: ${unlisted.join(", ")}`);
    }
    return SUITES;
}

/** Older observation scripts, deliberately excluded. */
const LEGACY = ["e2e-interact.mjs", "e2e-smoke.mjs", "e2e-screenshot-perf.mjs"];

const suites = selectSuites();
const results = [];

for (const suite of suites) {
    console.log(`\n=== ${suite} ===`);
    const run = spawnSync(process.execPath, [join(testsDir, suite)], {
        stdio: "inherit",
        env: { ...process.env, FB2K_E2E_RESULTS_DIR: resultsDir },
    });
    results.push({ suite, code: run.status ?? 1 });
}

const failed = results.filter((entry) => entry.code === 1);
const blocked = results.filter((entry) => entry.code === 2);
const other = results.filter((entry) => entry.code > 2);

console.log("\n=== e2e summary ===");
for (const entry of results) {
    const label =
        entry.code === 0
            ? "PASS"
            : entry.code === 1
              ? "FAIL"
              : entry.code === 2
                ? "BLOCKED"
                : `EXIT ${entry.code}`;
    console.log(`[${label}] ${entry.suite}`);
}
console.log(
    `${results.length} suites: ${results.length - failed.length - blocked.length - other.length} passed, ` +
        `${failed.length} failed, ${blocked.length} blocked${other.length ? `, ${other.length} crashed` : ""}`,
);
console.log(`summaries: ${resultsDir}`);

process.exit(failed.length + blocked.length + other.length > 0 ? 1 : 0);
