#include "pch.h"
#include "window/MenuOverlayHost.h"
#include "window/WindowManager.h"
#include "core/WebViewContext.h"
#include "api/BridgeCore.h"
#include "webview/WebViewHost.h"
#include "utils/GuidUtils.h"
#include "utils/I18n.h"
#include "window/MenuOverlayPage.inl"
#include "window/WindowChromeTrace.h"
#include <sstream>

// ============================================
// Self-drawn menu overlay host (renderer + submenu + keyboard nav).
// Page sources: src/window/menu-overlay/ ; generated by scripts/gen_menu_overlay_page.mjs
// ============================================

namespace {
    std::wstring BuildMenuOverlayHtml() {
        return BuildMenuOverlayHtmlFromSources();
    }

    // SPI_GETMENUDROPALIGNMENT：系统返回 TRUE 表示菜单相对锚点【右对齐】，
    // 即整块菜单朝光标左侧展开（左手模式）。读取失败按默认的向右展开处理。
    bool ReadMenuDropAlignLeft() {
        BOOL rightAligned = FALSE;
        if (!SystemParametersInfoW(SPI_GETMENUDROPALIGNMENT, 0, &rightAligned, 0)) {
            return false;
        }
        return rightAligned != FALSE;
    }

    // SPI_GETMENUSHOWDELAY：系统子菜单悬停展开延迟（毫秒），渲染器据此对齐原生手感。
    // 读取失败回退 Windows 默认 400ms；注册表可被写成任意值，故仍 clamp 上限。
    constexpr int kMenuShowDelayFallbackMs = 400;
    constexpr int kMenuShowDelayMaxMs = 5000;
    int ReadMenuShowDelayMs() {
        DWORD delay = 0;
        if (!SystemParametersInfoW(SPI_GETMENUSHOWDELAY, 0, &delay, 0)) {
            return kMenuShowDelayFallbackMs;
        }
        if (delay > static_cast<DWORD>(kMenuShowDelayMaxMs)) return kMenuShowDelayMaxMs;
        return static_cast<int>(delay);
    }
}

// ---------- MenuOverlayWindow ----------

void MenuOverlayWindow::OnWebViewReady() {
    PopupWindow::OnWebViewReady();
    if (!readyHtml_.empty()) {
        NavigateToString(readyHtml_);
    }
    if (webViewReadyCallback_) {
        webViewReadyCallback_();
    }
}

// ---------- MenuOverlayHost ----------

MenuOverlayHost& MenuOverlayHost::GetInstance() {
    static MenuOverlayHost instance;
    return instance;
}

bool MenuOverlayHost::EnsureCreated() {
    PFC_ASSERT(core_api::is_main_thread());
    if (overlay_ && overlayHwnd_ && IsWindow(overlayHwnd_)) {
        return true;
    }

    overlay_ = std::make_unique<MenuOverlayWindow>();
    overlay_->SetReadyHtml(BuildMenuOverlayHtml());

    PopupWindow::CreateParams params;
    params.url = "";
    params.width = 16;
    params.height = 16;
    params.x = 0;
    params.y = 0;
    params.title = "MenuOverlay";
    params.resizable = false;
    params.frame = false;
    params.transparent = true;
    params.alwaysOnTop = true;
    params.showInTaskbar = false;
    params.beforeClose = false;
    // 豁免 CreateParams 默认的 200×150 DIP 最小尺寸：菜单窗必须严格贴合测量出的
    // 内容尺寸。窗口样式含 WS_CAPTION(WS_DLGFRAME)，DefWindowProc 会按
    // WM_GETMINMAXINFO 钳制程序化 SetWindowPos——小菜单（如 min-width:170px）
    // 若被钳到 200 DIP 宽，右/下缘会露出内容盖不住的裸 DWM 材质带。
    params.minWidth = 1;
    params.minHeight = 1;

    params.hasBehavior = true;
    params.behavior = {
        {"noActivate", false},
        {"owner", "none"},
        {"showInTaskbar", false},
        {"showInAltTab", false},
        {"keepVisibleOnShowDesktop", true}
    };
    params.hasBackdropPolicy = true;
    // 自绘菜单系统级亚克力（DWM backdrop）。overlay 已 transparent=true，默认不透明的
    // .fb-menu 背景（#2b2b2b）仍完全遮住亚克力 → 默认视觉零回归；前端把 .fb-menu 背景
    // 改半透明后才透出亚克力。active/inactive 均用 acrylic：菜单弹出期间宿主窗口可能不持
    // 前台激活（noActivate 行为 / 任务栏交互），inactive 同样保亚克力，避免失焦瞬间掉成纯色。
    // 仅改 backdrop 材质，未触碰 transparent 标志与窗口几何 / 定位 / 不-resize 逻辑
    // （浮任务栏不压暗 / 防闪烁固定窗）。注意：此 overlay 由 tray
    // （ContentSized 小窗）与 menu.show（FullscreenOverlay 全屏透明窗）共用，backdrop 在此
    // 一次性设定；全屏透明区在 acrylic 下的观感建议真机验证。
    params.backdropPolicy = {
        {"activeEffect", "acrylic"},
        {"inactiveEffect", "acrylic"},
        {"darkMode", true}
    };

    HWND mainHwnd = core_api::get_main_window();
    HWND hwnd = overlay_->Create(params, kOverlayWindowId, mainHwnd);
    if (!hwnd) {
        overlay_.reset();
        overlayHwnd_ = nullptr;
        console::print("[MenuOverlayHost] EnsureCreated failed: Create returned null");
        return false;
    }
    overlayHwnd_ = hwnd;

    overlay_->SetSuppressLifecycleBroadcast(true);
    overlay_->SetMenuDismissCallback([](const std::string& reason, HWND other) {
        MenuOverlayHost::GetInstance().OnRootDismissRequested(reason, other);
    });

    ShowWindow(overlayHwnd_, SW_HIDE);
    console::print("[MenuOverlayHost] overlay created and hidden (pooled)");
    return true;
}

std::string MenuOverlayHost::Show(const json& items, int screenX, int screenY,
                                  SelectSink onSelect, DismissSink onDismiss,
                                  const MenuShowOptions& opts, ValueSink onValue) {
    PFC_ASSERT(core_api::is_main_thread());
    if (!EnsureCreated()) {
        return std::string();
    }

    // 交错策略：已有菜单在显示【或处于退场动画期】时，先强制立即收尾旧菜单，再写入新 sink，
    // 杜绝新 sink 被误用于旧菜单的 dismiss。退场期 visible_&&closing_ 时，Hide("replaced") 会被
    // if(closing_) return 挡掉，旧菜单不会被收回 → 池化单窗会出现旧菜单淡出同时显示新菜单的叠影。
    // 故直接 ForceHideImmediate 强制同步收尾（绕过 animate 判定），旧 sink/ownerMode 分发 dismiss。
    if (visible_ || closing_) {
        ForceHideImmediate();
    }
    selectSink_ = std::move(onSelect);
    dismissSink_ = std::move(onDismiss);
    valueSink_ = std::move(onValue);
    ownerMode_ = static_cast<bool>(selectSink_) || static_cast<bool>(dismissSink_)
              || static_cast<bool>(valueSink_);
    windowModel_ = opts.windowModel;  // 窗口几何模型（与 ownerMode_ 正交）
    overlayModel_ = opts.overlayModel;  // DOM 输入模型（与 windowModel_ / ownerMode_ 正交）
    currentCss_ = opts.css;            // 前端样式接管（S-CSS）：本次 show 的前端 CSS（每次 show 覆盖即复位）
    currentCssReplace_ = opts.cssReplace;  // replace 模式开关（默认 false = override 叠加）
    currentCloseAnimationMs_ = opts.closeAnimationMs;  // 退场动画时长（0=立即隐藏不动画，零回归）
    currentBackdrop_ = opts.backdrop;
    currentBackdropDarkMode_ = opts.backdropDarkMode;
    currentAnchorPolicy_ = menu_overlay_geometry::ParseAnchorPolicy(opts.anchorPolicy);
    currentDropAlignLeft_ = ReadMenuDropAlignLeft();  // 快照左手模式，供异步 measure 定位复用

    POINT pt{ screenX, screenY };
    HMONITOR mon = MonitorFromPoint(pt, MONITOR_DEFAULTTONEAREST);
    MONITORINFO mi{};
    mi.cbSize = sizeof(mi);
    RECT work{ 0, 0, GetSystemMetrics(SM_CXSCREEN), GetSystemMetrics(SM_CYSCREEN) };
    RECT full = work;
    if (mon && GetMonitorInfo(mon, &mi)) {
        work = mi.rcWork;
        full = mi.rcMonitor;
    }

    currentItems_ = json::array();
    currentZones_ = json::array();
    // Assign an opaque single-use token per actionable node and (re)build the
    // token table BEFORE the renderer pulls state. currentItems_/currentZones_
    // are mutated in place: each node gains a `_token`, internal `_origin` /
    // `_builtinAction` are stripped. select / valueChanged resolve only through
    // this table. The generator checks the GUID HRESULT; the table retries on
    // collision. If a unique token cannot be assigned, the build fails
    // transactionally and we abort the Show — never expose a partial token set.
    auto guidGen = []() -> std::optional<std::string> {
        GUID guid{};
        if (FAILED(CoCreateGuid(&guid))) return std::nullopt;
        return GuidUtils::GuidToString(guid);
    };
    // `ownerMode_` is set only by the tray-owned C++ path. Public `menu.show`
    // has no owner sinks and therefore cannot promote private JSON action fields.
    const bool trustInternalActionFields = ownerMode_;
    bool tokensOk = false;
    if (overlayModel_ == MenuOverlayModel::TrayZones) {
        currentZones_ = items.is_array() ? items : json::array();
        tokensOk = tokenTable_.RebuildZones(currentZones_, guidGen, trustInternalActionFields);
    } else {
        currentItems_ = items.is_array() ? items : json::array();
        tokensOk = tokenTable_.Rebuild(currentItems_, guidGen, trustInternalActionFields);
    }
    if (!tokensOk) {
        tokenTable_.Clear();
        currentItems_ = json::array();
        currentZones_ = json::array();
        selectSink_ = nullptr;
        dismissSink_ = nullptr;
        valueSink_ = nullptr;
        ownerMode_ = false;
        console::print("[MenuOverlayHost] Show aborted: opaque token assignment failed");
        return std::string();
    }

    // A pooled submenu may still be visible from the preceding session. Hide
    // it before the new root receives focus so the two HWNDs never overlap
    // across menu generations.
    HideSubmenuWindow(false, false, false);

    if (windowModel_ == MenuWindowModel::ContentSized) {
        // ContentSized：先以临时尺寸在光标附近显示（渲染器 opacity:0 测量），
        // 收到 menu.__ready 后由 OnContentMeasured 定位到内容尺寸（rcMonitor 边界，可压任务栏）。
        measureGate_.Begin();
        placedGeometry_.reset();
        contentVirtualOrigin_ = POINT{};
        openSubmenuVirtualRect_.reset();
        openSubmenuParentToken_.clear();
        lastSubmenuPanelSequence_ = 0;
        pendingSubmenuPanelSequence_.reset();
        overlay_->ClearContentRegion();
        pendingAnchor_ = pt;
        anchorClientX_ = 0;   // 内容窗：菜单贴客户区原点，渲染器 placeRoot 退化
        anchorClientY_ = 0;
        const int workW = work.right - work.left;
        const int workH = work.bottom - work.top;
        const int tmpW = workW < 480 ? workW : 480;
        const int tmpH = workH < 720 ? workH : 720;
        // 临时窗放屏幕外测量（off-screen + opacity:0 双保险），由 OnContentMeasured 再移到光标处，
        // 彻底消除“先在上方固定高度出现、测量后跳到光标”的可见跳变（用户反馈 bug1）。
        SetWindowPos(overlayHwnd_, HWND_TOPMOST, -32000, -32000, tmpW, tmpH, SWP_NOACTIVATE);
    } else {
        // FullscreenOverlay（现状）：铺满工作区。
        measureGate_.Cancel();
        placedGeometry_.reset();
        contentVirtualOrigin_ = POINT{};
        openSubmenuVirtualRect_.reset();
        openSubmenuParentToken_.clear();
        lastSubmenuPanelSequence_ = 0;
        pendingSubmenuPanelSequence_.reset();
        overlay_->ClearContentRegion();
        const int w = work.right - work.left;
        const int h = work.bottom - work.top;
        anchorClientX_ = screenX - work.left;
        anchorClientY_ = screenY - work.top;
        SetWindowPos(overlayHwnd_, HWND_TOPMOST, work.left, work.top, w, h, SWP_NOACTIVATE);
    }

    // 记录交接前的前台窗口（FinalizeHide 归还激活与键盘焦点用）。菜单替换菜单时
    // 前台可能已在菜单面上，此时保留上一轮记录，避免"还给菜单自己"。
    const HWND fgBeforeShow = GetForegroundWindow();
    if (fgBeforeShow && fgBeforeShow != overlayHwnd_ && fgBeforeShow != submenuHwnd_) {
        previousForeground_ = fgBeforeShow;
    }
    // handoff 窗口期：SetForegroundWindow 同步派发宿主的 WM_NCACTIVATE/WM_ACTIVATE，
    // 宿主经 ShouldHoldOwnerActivation 识别"失活是让位给菜单"从而维持激活观感。
    activationHandoff_ = true;
    ShowWindow(overlayHwnd_, SW_SHOW);
    SetForegroundWindow(overlayHwnd_);
    activationHandoff_ = false;
    SetWindowPos(overlayHwnd_, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);

    // 运行时按本次 config 应用 DWM 系统背景：池化 overlay 被 tray（ContentSized）与
    // menu.show（FullscreenOverlay）共用，逐 show 覆盖。须在 ShowWindow 之后调，避开
    // “隐藏窗口设 backdrop 不初始化合成”的坑（EnsureCreated 的 acrylic 仅作创建默认）。
    // menu.show 走默认 opts（backdrop=acrylic）= 与原创建期行为等价；失败仅忽略。
    if (overlay_) {
        std::string bderr;
        overlay_->UpdateBackdropPolicy(
            json{ {"activeEffect", opts.backdrop}, {"inactiveEffect", opts.backdrop}, {"darkMode", opts.backdropDarkMode} },
            bderr);
        // 圆角逐 show 重申（写入幂等）：两种窗口模型统一 ROUND（8 DIP）——Win11 的
        // 右键菜单标准半径就是 ROUND；ROUNDSMALL(4 DIP) 是 tooltip 级半径，曾误用
        // 导致窗口 R 明显小于画布设计（用户实测反馈）。
        overlay_->SetCornerPreferenceOverride(PopupWindow::kCornerRound);
    }
    if (overlay_->IsWebViewReady()) {
        if (auto* wv = overlay_->GetWebView()) {
            RECT rc{};
            GetClientRect(overlayHwnd_, &rc);
            wv->SetVisible(true);
            wv->Resize(rc);
            if (auto* ctrl = wv->GetController()) {
                ctrl->NotifyParentWindowPositionChanged();
                ctrl->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);  // 让 WebView 内容获键盘焦点（菜单可即时键盘导航）
            }
        }
    }

    currentMenuId_ = "menu-" + std::to_string(++showSeq_);
    visible_ = true;
    showTick_ = GetTickCount64();
    ArmWatchdog();
    if (windowModel_ == MenuWindowModel::ContentSized) {
        ArmMeasureTimer();  // 测量回报兜底
    }

    if (overlay_->IsWebViewReady() && overlay_->GetBridge()) {
        overlay_->GetBridge()->EmitEvent("menu:show", { {"menuId", currentMenuId_} });
    }

    console::printf("[MenuOverlayHost] Show id=%s items=%d model=%s anchorClient=(%d,%d)",
                    currentMenuId_.c_str(), (int)currentItems_.size(),
                    windowModel_ == MenuWindowModel::ContentSized ? "content" : "fullscreen",
                    anchorClientX_, anchorClientY_);
    return currentMenuId_;
}

void MenuOverlayHost::Hide(const std::string& reason) {
    // dismiss 链取证：放在防抖/早退之前，锁死"Hide 被谁吞"——
    // sinceShowMs<250 的 blur 走防抖；!visible_/closing_ 走幂等早退。
    // 本文件的取证日志统一经 WindowChromeTrace::EmitAuxiliaryLine 输出：默认关闭，
    // 置环境变量 FOO_UI_WEBVIEW2_WINDOW_TRACE=1 开启。禁止改回 console::printf——
    // 它是 pfc 精简实现，只认 %s/%d/%u/%x/%c，%p/%llu 按字面输出且不消费变参，
    // 错位后 %s 读野指针会崩（failure_00000211 实锤），故一律 ostringstream 拼串。
    {
        std::ostringstream oss;
        oss << "[MenuOverlayHost] Hide enter reason=" << reason
            << " visible=" << (visible_ ? 1 : 0)
            << " closing=" << (closing_ ? 1 : 0)
            << " sinceShowMs=" << (GetTickCount64() - showTick_);
        WindowChromeTrace::EmitAuxiliaryLine(oss.str());
    }
    if (reason == "blur" && visible_ && (GetTickCount64() - showTick_) < 250) {
        return;
    }
    if (!visible_) {
        return;
    }
    if (closing_) {
        // 已在退场动画期：幂等吞掉重入 / 多源 dismiss（blur/outside/timeout 等），
        // 由 close-timer → FinalizeHide 收尾（防淡出期重复触发 / 重入）。
        return;
    }

    // The root can fade, but the independent DWM-backed submenu must never
    // remain visible or interactive during that fade. Clear its pending/open
    // state before either root-close branch; no focus restore or root renderer
    // notification is allowed because this is a whole-menu close, not a child
    // return. A late child-ready callback is rejected by the closing/state gates.
    const bool windowOk = overlayHwnd_ && IsWindow(overlayHwnd_);
    const auto closePolicy = menu_overlay_geometry::ResolveRootClosePolicy(
        reason, windowOk, currentCloseAnimationMs_);
    if (closePolicy.hideSubmenuImmediately) {
        HideSubmenuWindow(closePolicy.restoreRootFocus, closePolicy.notifyRootRenderer,
                          closePolicy.clearSubmenuStateImmediately);
    }

    if (closePolicy.animateRoot) {
        // 进入 Closing：visible_ 仍 true；发内部事件 menu:__hide 通知渲染器播退场；ArmCloseTimer
        // 延迟到 close-timer 收尾。此刻【不】SW_HIDE、【不】分发 dismiss（留到 FinalizeHide）。
        // 注意：select 的 selectSink_ 已在 OnSelect 里先于 Hide("select") 派发（动作不被动画延迟）。
        closing_ = true;
        pendingCloseReason_ = reason;
        if (overlay_ && overlay_->IsWebViewReady() && overlay_->GetBridge()) {
            overlay_->GetBridge()->EmitEvent("menu:__hide", { {"menuId", currentMenuId_} });  // 内部事件（overlay 私有 bridge→渲染器）；:__ 前缀=codegen 不进公共 events.ts
        }
        ArmCloseTimer(currentCloseAnimationMs_);
        console::printf("[MenuOverlayHost] Hide(animate) id=%s reason=%s ms=%d",
                        currentMenuId_.c_str(), reason.c_str(), currentCloseAnimationMs_);
        return;
    }

    // 立即路径（现状同步隐藏，零回归）：未开动画 / replaced / timeout / measure_timeout / 窗口失效等。
    FinalizeHide(reason);
}

void MenuOverlayHost::OnDismissRequested(HWND caller, const std::string& reason) {
    if (!visible_ || closing_) {
        return;
    }
    if (caller && caller == submenuHwnd_ && (reason == "escape" || reason == "submenu-left")) {
        HideSubmenuWindow(true, true);
        return;
    }
    Hide(reason);
}

void MenuOverlayHost::FinalizeHide(const std::string& reason) {
    // 两段式 Hide 的同步收尾（立即路径 / close-timer 收尾共用）。
    // 先捕获并复位状态（务必在 ShowWindow 之前）：ShowWindow(SW_HIDE) 会同步触发
    // WM_KILLFOCUS → dismiss 回调 → 重入 Hide。若状态后置清理，重入会先清掉 ownerMode_，
    // 外层继续时误判为非 owner 而泄漏 menu:dismiss。先置 visible_=false 且 closing_=false 让重入早退。
    visible_ = false;
    closing_ = false;
    // 在隐藏任何菜单面之前采样前台归属：SW_HIDE 会让系统自行转移前台，之后就无从
    // 判断"关闭时前台是否还在菜单面上"。
    const HWND fgAtClose = GetForegroundWindow();
    measureGate_.Cancel();
    placedGeometry_.reset();
    contentVirtualOrigin_ = POINT{};
    HideSubmenuWindow(false);
    lastSubmenuPanelSequence_ = 0;
    pendingSubmenuPanelSequence_.reset();
    pendingCloseReason_.clear();
    const std::string closedId = currentMenuId_;
    currentMenuId_.clear();
    currentItems_ = json::array();
    currentZones_ = json::array();
    overlayModel_ = MenuOverlayModel::LegacyItems;
    tokenTable_.Clear();             // opaque tokens are single-use per show; invalidate now
    currentCss_.clear();              // 前端样式接管（S-CSS）：本次 show 结束复位，防泄漏到下次
    currentCssReplace_ = false;

    // owner-mode：dismiss 改走 sink（tray 默认无 sink = 原生菜单关闭不发事件），
    // 不发公共 menu:dismiss；menu.* 普通模式维持现状。
    // sink 生命周期：本次 show 结束即释放（避免泄漏到下次 menu.show）。
    const bool wasOwnerMode = ownerMode_;
    DismissSink dismissSink = dismissSink_;
    selectSink_ = nullptr;
    dismissSink_ = nullptr;
    valueSink_ = nullptr;
    ownerMode_ = false;

    KillWatchdog();
    KillMeasureTimer();
    KillCloseTimer();
    if (overlay_) {
        overlay_->ClearContentRegion();
    }
    // 归还激活：Esc/select/看门狗等路径关闭时前台仍在菜单面上（含 Chromium 内部
    // 子 HWND，按 GA_ROOT 归一判定），显式还给打开菜单前的窗口（激活观感与键盘
    // 焦点一并回到调用方）。外点击/切他窗时系统已把前台转走，不做干预。
    if (IsMenuSurfaceWindow(fgAtClose) &&
        previousForeground_ && IsWindow(previousForeground_) &&
        IsWindowVisible(previousForeground_)) {
        SetForegroundWindow(previousForeground_);
    }
    previousForeground_ = nullptr;
    activationHandoff_ = false;
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        ShowWindow(overlayHwnd_, SW_HIDE);
        // 必须在 SW_HIDE 之后：SW_HIDE 同步触发 WM_KILLFOCUS → dismiss → 重入 Hide
        //（见本函数开头注释），此刻 visible_/closing_ 已复位，重入会早退，收口不被打断。
        CollapseWebViewSurface(overlay_.get(), overlayHwnd_);
    }

    if (wasOwnerMode) {
        if (dismissSink) {
            try { dismissSink(reason); } catch (...) {}
        }
    } else {
        BridgeCore::GetInstance().EmitEvent("menu:dismiss", {
            {"menuId", closedId},
            {"reason", reason}
        });
    }
    console::printf("[MenuOverlayHost] FinalizeHide id=%s reason=%s owner=%d",
                    closedId.c_str(), reason.c_str(), (int)wasOwnerMode);
}

void MenuOverlayHost::ForceHideImmediate() {
    // Show 取消挂起关闭复用：绕过 animate 判定，直接同步收尾。退场期 visible_&&closing_ 时，
    // 新 Hide("replaced") 会被 if(closing_) return 挡掉，故 Show 不能依赖 Hide("replaced")。
    // 用 "replaced" 收尾（与历史 Show 调 Hide("replaced") 行为一致；tray owner-mode 无 dismiss sink，
    // reason 仅记录用；menu.show 因 closeAnimationMs=0 永不进 Closing，此处恒等于历史立即替换路径）。
    if (!visible_ && !closing_) {
        return;
    }
    FinalizeHide("replaced");
}

void MenuOverlayHost::OnSelect(const std::string& token) {
    // Reject during the exit animation (closing_): visible_ is still true then,
    // and the token set is not cleared until final teardown, so without this a
    // rapid repeat click could re-run the same action.
    if (!visible_ || closing_) {
        return;
    }
    auto action = tokenTable_.ResolveSelect(token);
    if (!action.has_value()) {
        return;   // unknown / expired token, disabled item, submenu parent, or value control
    }
    // First accepted select wins: invalidate the whole token set NOW so a
    // re-entrant / rapid second select resolves to nothing.
    tokenTable_.Clear();
    const std::string menuId = currentMenuId_;
    if (ownerMode_) {
        // owner-mode：选中改走 sink（→ tray:menuItemClicked），按可信 origin 路由
        if (selectSink_) {
            try { selectSink_(*action); } catch (...) {}
        }
    } else {
        // 公共 menu.show：仅发索引里的 publicId（永不回 token）
        BridgeCore::GetInstance().EmitEvent("menu:select", {
            {"menuId", menuId},
            {"itemId", action->publicId}
        });
    }
    console::printf("[MenuOverlayHost] Select id=%s item=%s owner=%d",
                    menuId.c_str(), action->publicId.c_str(), (int)ownerMode_);
    Hide("select");
}

void MenuOverlayHost::OnValueChanged(const std::string& token, int value) {
    // 富控件（rating/slider/segmented）值变更：解析 token → 按控件类型校验值 → 经
    // valueSink_ 回报，【不关闭菜单】。无 sink / 非法 token / 越界值静默忽略。
    // 退场动画期（closing_）拒绝，避免淡出中改值。
    if (!visible_ || closing_) {
        return;
    }
    auto publicId = tokenTable_.ResolveValue(token, value);
    if (!publicId.has_value()) {
        return;   // not a value control, out-of-range value, disabled item, or unknown token
    }
    if (ownerMode_) {
        if (valueSink_) {
            try { valueSink_(*publicId, value); } catch (...) {}
        }
    } else {
        // 公共 menu.show：与 menu:select 同口径，仅发索引里的 publicId（永不回 token）。
        // 值变更不关闭菜单，故此处不调 Hide。
        BridgeCore::GetInstance().EmitEvent("menu:valueChanged", {
            {"menuId", currentMenuId_},
            {"itemId", *publicId},
            {"value", value}
        });
    }
    console::printf("[MenuOverlayHost] ValueChanged item=%s value=%d owner=%d",
                    publicId->c_str(), value, (int)ownerMode_);
}

bool MenuOverlayHost::OnContentMeasured(const menu_overlay_geometry::MeasureReport& report) {
    PFC_ASSERT(core_api::is_main_thread());
    if (!visible_ || closing_ || windowModel_ != MenuWindowModel::ContentSized ||
        !measureGate_.IsAwaiting()) {
        return false;
    }
    const bool hasSubmenu = HasFirstLevelSubmenu();
    if (!menu_overlay_geometry::IsValidMeasureReport(report, hasSubmenu)) {
        return false;
    }

    HMONITOR mon = MonitorFromPoint(pendingAnchor_, MONITOR_DEFAULTTONEAREST);
    MONITORINFO mi{};
    mi.cbSize = sizeof(mi);
    RECT full{ 0, 0, GetSystemMetrics(SM_CXSCREEN), GetSystemMetrics(SM_CYSCREEN) };
    RECT work = full;
    if (mon && GetMonitorInfo(mon, &mi)) {
        full = mi.rcMonitor;   // rcMonitor 边界 → 可压任务栏
        work = mi.rcWork;
    }

    auto placement = menu_overlay_geometry::ComputePlacement(
        report, hasSubmenu, work.right - work.left, work.bottom - work.top);
    if (!placement.has_value()) {
        return false;
    }
    const int virtualW = placement->viewportW;
    const int virtualH = placement->viewportH;

    // 定位交由纯函数决策（可单测）：bottomUp = 托盘现状（根底贴光标向上展开）；
    // cursor = 标准右键菜单——锚定语义作用于根面板本身（根边缘贴光标），右缘
    // 翻转时子菜单槽换到根左侧（anchored.subOnLeft），根与光标不再有子槽宽偏差。
    const auto anchored = menu_overlay_geometry::ComputeAnchoredOrigin(
        menu_overlay_geometry::Point{pendingAnchor_.x, pendingAnchor_.y},
        *placement,
        menu_overlay_geometry::Rect{full.left, full.top,
                                    full.right - full.left, full.bottom - full.top},
        currentAnchorPolicy_, currentDropAlignLeft_);
    placement->subOnLeft = anchored.subOnLeft;
    const int x = anchored.origin.x;
    const int y = anchored.origin.y;

    contentVirtualOrigin_ = POINT{x, y};
    // The root is a tight real HWND. Do not reserve an invisible native slot
    // and do not depend on SetWindowRgn to hide a DWM system backdrop: Windows
    // 11 composes DWMSBT_TRANSIENTWINDOW across the HWND rectangle.
    if (!ApplyRootContentWindow(*placement)) {
        console::printf("[MenuOverlayHost] ContentMeasured root window failed id=%s",
                        currentMenuId_.c_str());
        return false;
    }
    if (!measureGate_.TryConsume(true)) {
        if (overlay_) overlay_->ClearContentRegion();
        return false;
    }
    KillMeasureTimer();
    placedGeometry_ = placement;
    SyncWebViewToClient(overlay_.get(), overlayHwnd_);
    if (overlay_->IsWebViewReady() && overlay_->GetBridge()) {
        overlay_->GetBridge()->EmitEvent("menu:__placed", {
            {"menuId", currentMenuId_},
            {"first", true},
            {"geometry", BuildRootGeometryJson(*placement)}
        });  // overlay-private bridge event; not part of public SDK events
    }
    console::printf("[MenuOverlayHost] ContentMeasured root id=%s win=(%d,%d) pos=(%d,%d) virtual=(%d,%d)",
                    currentMenuId_.c_str(), placement->rootSlotW, placement->rootVisibleH,
                    x, y + placement->rootTop, virtualW, virtualH);
    return true;
}

bool MenuOverlayHost::OnSubmenuPanelChanged(
    const menu_overlay_geometry::SubmenuPanelRequest& request,
    const std::string& parentToken) {
    // 子菜单握手取证：参数 + 判定去向。
    // outcome ∈ reject:*（拒绝原因）/ hide-accept / show-accept。
    const auto logPanel = [&](const char* outcome) {
        std::ostringstream oss;
        oss << "[MenuOverlayHost] SubPanel visible=" << (request.visible ? 1 : 0)
            << " seq=" << request.sequence
            << " rect=(" << request.x << "," << request.y << ","
            << request.w << "," << request.h << ")"
            << " token=" << parentToken.substr(0, 8)
            << " lastSeq=" << lastSubmenuPanelSequence_
            << " pendingSeq="
            << (pendingSubmenuPanelSequence_ ? std::to_string(*pendingSubmenuPanelSequence_) : "-")
            << " outcome=" << outcome;
        WindowChromeTrace::EmitAuxiliaryLine(oss.str());
    };
    // Root close clears pending/open child state before a possible fade. Never
    // accept renderer hover reports while closing: an old ready/hover callback
    // must not resurrect a submenu HWND after its root started disappearing.
    if (!visible_ || closing_) {
        logPanel("reject:not-visible-or-closing");
        return false;
    }
    const auto update = menu_overlay_geometry::EvaluateSubmenuPanelUpdate(
        windowModel_ == MenuWindowModel::ContentSized, placedGeometry_, request);
    const auto newestAppliedOrPending = pendingSubmenuPanelSequence_.value_or(lastSubmenuPanelSequence_);
    if (!update.accepted || !placedGeometry_.has_value()) {
        logPanel("reject:update-or-geometry");
        return false;
    }
    if (!request.visible) {
        if (!menu_overlay_geometry::IsNewerSubmenuPanelSequence(newestAppliedOrPending, request.sequence)) {
            logPanel("reject:stale-hide-seq");
            return false;
        }
        HideSubmenuWindow(false);
        lastSubmenuPanelSequence_ = request.sequence;
        pendingSubmenuPanelSequence_.reset();
        logPanel("hide-accept");
        return true;
    }
    if (!update.submenuWindow.has_value() || parentToken.empty() ||
        !FindSubmenuItems(parentToken).has_value()) {
        logPanel("reject:window-token-or-items");
        return false;
    }
    // A retry for the same still-pending renderer frame is accepted; a stale
    // older sequence remains rejected. This is needed while a newly created
    // child WebView reaches its first hidden ready state.
    if (request.sequence != newestAppliedOrPending &&
        !menu_overlay_geometry::IsNewerSubmenuPanelSequence(newestAppliedOrPending, request.sequence)) {
        logPanel("reject:stale-show-seq");
        return false;
    }
    openSubmenuVirtualRect_ = update.submenuWindow;
    openSubmenuParentToken_ = parentToken;
    pendingSubmenuPanelSequence_ = request.sequence;
    if (!EnsureSubmenuCreated()) {
        logPanel("reject:create-failed");
        return false;
    }
    // Each open first refreshes the hidden renderer state. It acknowledges the
    // existing `menu.__submenuPanel` endpoint with `ready:true` before this HWND is made visible, avoiding a blank
    // DWM-material flash and stale items when hover switches siblings quickly.
    HideSubmenuWindow(false, false, false);
    if (submenuOverlay_ && submenuOverlay_->IsWebViewReady() && submenuOverlay_->GetBridge()) {
        submenuOverlay_->GetBridge()->EmitEvent("menu:show", {{"menuId", currentMenuId_}});
    }
    logPanel("show-accept");
    return true;
}

bool MenuOverlayHost::OnSubmenuSurfaceReady(HWND caller, const std::string& parentToken) {
    // 握手取证：逐条件展开，锁死 ready 回执被拒的确切原因。
    {
        std::ostringstream oss;
        oss << "[MenuOverlayHost] SubReady callerOk=" << (caller == submenuHwnd_ ? 1 : 0)
            << " visible=" << (visible_ ? 1 : 0)
            << " closing=" << (closing_ ? 1 : 0)
            << " rect=" << (openSubmenuVirtualRect_.has_value() ? 1 : 0)
            << " token=" << parentToken.substr(0, 8)
            << " openToken=" << openSubmenuParentToken_.substr(0, 8)
            << " tokenMatch=" << (!parentToken.empty() && parentToken == openSubmenuParentToken_ ? 1 : 0)
            << " pendingSeq="
            << (pendingSubmenuPanelSequence_ ? std::to_string(*pendingSubmenuPanelSequence_) : "-");
        WindowChromeTrace::EmitAuxiliaryLine(oss.str());
    }
    if (caller != submenuHwnd_ || !visible_ || closing_ || !openSubmenuVirtualRect_.has_value() ||
        parentToken.empty() || parentToken != openSubmenuParentToken_ ||
        !pendingSubmenuPanelSequence_.has_value()) {
        return false;
    }
    if (!ShowSubmenuWindow(*openSubmenuVirtualRect_, openSubmenuParentToken_)) {
        WindowChromeTrace::EmitAuxiliaryLine("[MenuOverlayHost] SubReady rejected: ShowSubmenuWindow failed");
        return false;
    }
    lastSubmenuPanelSequence_ = *pendingSubmenuPanelSequence_;
    pendingSubmenuPanelSequence_.reset();
    if (overlay_ && overlay_->IsWebViewReady() && overlay_->GetBridge()) {
        overlay_->GetBridge()->EmitEvent("menu:__submenuOpened", {{"menuId", currentMenuId_}});
    }
    return true;
}

json MenuOverlayHost::GetMenuStateJson(HWND caller) const {
    const bool isSubmenuSurface = caller && caller == submenuHwnd_;
    json st = {
        {"visible", visible_},
        {"menuId", currentMenuId_},
        {"anchorX", anchorClientX_},
        {"anchorY", anchorClientY_},
        // 窗口几何模型：渲染器据此分支（contentSized = 去 #block + placeRoot 退化 + 测量回报）。
        {"windowModel", isSubmenuSurface ? "submenu" :
            (windowModel_ == MenuWindowModel::ContentSized ? "contentSized" : "fullscreen")},
        {"surface", isSubmenuSurface ? "submenu" : "root"},
        // Overlay DOM 输入模型（显式，禁止由 windowModel 猜测）。
        {"overlayModel", overlayModel_ == MenuOverlayModel::TrayZones ? "trayZones" : "legacyItems"},
        {"layoutMode", overlayModel_ == MenuOverlayModel::TrayZones ? "zones" : "flat"},
        // 前端样式接管（S-CSS）：css = 前端注入样式字符串（写入 <style id="fb-user">）；
        // cssReplace = true 时 replace 模式（禁用默认样式，仅留 fb-user+fb-protected），false = override 叠加。
        {"css", currentCss_},
        {"cssReplace", currentCssReplace_},
        // 子菜单悬停展开延迟：直接下发系统 SPI_GETMENUSHOWDELAY，让自绘菜单的展开节奏
        // 与原生菜单一致（渲染器不得自定义默认值）。
        {"menuShowDelayMs", ReadMenuShowDelayMs()},
        // 屏幕阅读器文本语言：与 utils/I18n.h 同源，即 foobar2000 程序呈现语言
        // （探测核心字符串，失败时回退系统 UI 语言；可被偏好设置覆盖），
        // 与本组件其余原生界面文案保持一致。
        // 不用 navigator.language —— 那是 WebView2 自身的语言，可能与之不符。
        // 只有中/英两档，全部 zh-* (含繁体) 都归为 "zh"。
        {"locale", i18n::IsChineseLocale() ? "zh" : "en"}
    };
    if (isSubmenuSurface) {
        st["overlayModel"] = "legacyItems";
        st["layoutMode"] = "flat";
        st["zones"] = json::array();
        st["items"] = FindSubmenuItems(openSubmenuParentToken_).value_or(json::array());
        st["parentToken"] = openSubmenuParentToken_;
        if (openSubmenuVirtualRect_.has_value()) {
            st["geometry"] = {
                {"viewportW", openSubmenuVirtualRect_->w},
                {"viewportH", openSubmenuVirtualRect_->h},
                {"rootSlotW", openSubmenuVirtualRect_->w},
                {"subSlotW", 0},
                {"rootTop", 0}
            };
        }
    } else if (overlayModel_ == MenuOverlayModel::TrayZones) {
        st["zones"] = currentZones_;
        st["items"] = json::array();  // zones model: items unused
    } else {
        st["items"] = currentItems_;
        st["zones"] = json::array();
    }
    // 握手取证：C++ 侧记录 pull 响应摘要，
    // 与渲染器 render 分支（空内容 hide / submenu ready 回执）对照。
    {
        std::ostringstream oss;
        oss << "[MenuOverlayHost] StatePull surface=" << (isSubmenuSurface ? "submenu" : "root")
            << " visible=" << (visible_ ? 1 : 0)
            << " menuId=" << currentMenuId_
            << " itemsLen=" << st["items"].size()
            << " zonesLen=" << st["zones"].size();
        if (isSubmenuSurface) {
            oss << " openToken=" << openSubmenuParentToken_.substr(0, 8)
                << " geom=" << (openSubmenuVirtualRect_.has_value() ? 1 : 0);
        }
        WindowChromeTrace::EmitAuxiliaryLine(oss.str());
    }
    return st;
}

bool MenuOverlayHost::IsOverlayCaller(HWND caller) const {
    // The overlay's renderer messages arrive with _callerHwnd == overlayHwnd_
    // (WebViewPanel::HandleWebMessage injects the window hwnd_). Any other window
    // — or a call before the overlay exists — is rejected.
    return menu_action::IsSameOverlayWindow(caller, overlayHwnd_) ||
        menu_action::IsSameOverlayWindow(caller, submenuHwnd_);
}

bool MenuOverlayHost::IsRootOverlayCaller(HWND caller) const {
    return menu_action::IsSameOverlayWindow(caller, overlayHwnd_);
}

bool MenuOverlayHost::ShouldHoldOwnerActivation(HWND other) const {
    // 菜单不在场（含交接瞬间之外的创建期）一律不保持。
    if (!visible_ && !activationHandoff_) {
        return false;
    }
    // 菜单面 SetForegroundWindow 的同步窗口期：此刻宿主收到的失活消息必然是
    // 交接产物（WM_NCACTIVATE 的 lParam 不保证携带对端窗口，只能靠此兜底）。
    if (activationHandoff_) {
        return true;
    }
    // 稳态：仅当消息明确指认对端属于菜单面才保持。other 为空或指向外部窗口时
    // 一律放行失活——外点击/Alt-Tab 的变灰与 blur dismiss 语义必须保留。
    return IsMenuSurfaceWindow(other);
}

bool MenuOverlayHost::IsMenuSurfaceWindow(HWND hwnd) const {
    if (!hwnd) return false;
    // Chromium 的 MoveFocus/点击会把前台与激活对端落到 WebView 内部子 HWND
    //（Chrome_WidgetWin_*），必须归一到顶层窗再比较；顶层窗的 GA_ROOT 即自身。
    HWND root = GetAncestor(hwnd, GA_ROOT);
    const HWND target = root ? root : hwnd;
    return (overlayHwnd_ && target == overlayHwnd_) ||
           (submenuHwnd_ && target == submenuHwnd_);
}

bool MenuOverlayHost::ValidateMenuId(const std::string& menuId) const {
    // Only the currently-visible menu's id is accepted; a stale page report or a
    // forged id from another surface cannot drive select/dismiss/ready/value.
    return menu_action::IsCurrentMenuId(menuId, currentMenuId_, visible_);
}

bool MenuOverlayHost::HasFirstLevelSubmenu() const {
    const auto hasSubmenu = [](const json& items) {
        if (!items.is_array()) return false;
        for (const auto& item : items) {
            if (item.is_object() && item.contains("submenu") &&
                item["submenu"].is_array() && !item["submenu"].empty()) {
                return true;
            }
        }
        return false;
    };
    if (overlayModel_ == MenuOverlayModel::TrayZones) {
        if (!currentZones_.is_array()) return false;
        for (const auto& zone : currentZones_) {
            if (zone.is_object() && zone.contains("items") && hasSubmenu(zone["items"])) {
                return true;
            }
        }
        return false;
    }
    return hasSubmenu(currentItems_);
}

void MenuOverlayHost::Shutdown() {
    KillWatchdog();
    KillMeasureTimer();
    KillCloseTimer();
    visible_ = false;
    closing_ = false;
    measureGate_.Cancel();
    placedGeometry_.reset();
    contentVirtualOrigin_ = POINT{};
    HideSubmenuWindow(false);
    lastSubmenuPanelSequence_ = 0;
    pendingSubmenuPanelSequence_.reset();
    pendingCloseReason_.clear();
    currentMenuId_.clear();
    currentItems_ = json::array();
    currentZones_ = json::array();
    overlayModel_ = MenuOverlayModel::LegacyItems;
    tokenTable_.Clear();
    if (overlay_) {
        overlay_->ClearContentRegion();
        overlay_->Destroy();
        overlay_.reset();
    }
    overlayHwnd_ = nullptr;
    if (submenuOverlay_) {
        submenuOverlay_->Destroy();
        submenuOverlay_.reset();
    }
    submenuHwnd_ = nullptr;
}

bool MenuOverlayHost::ApplyRootContentWindow(const menu_overlay_geometry::Placement& placement) {
    if (!overlayHwnd_ || !IsWindow(overlayHwnd_)) return false;
    const auto root = menu_overlay_geometry::RootWindowExtent(placement);
    if (root.w <= 0 || root.h <= 0) return false;
    if (!SetWindowPos(overlayHwnd_, HWND_TOPMOST,
                      contentVirtualOrigin_.x + root.x, contentVirtualOrigin_.y + root.y,
                      root.w, root.h, SWP_NOACTIVATE)) {
        return false;
    }
    // A tight HWND is the visual contract. Clear any region left from prior
    // pooled shows; the region is retained only for unrelated popup consumers,
    // never as the correctness mechanism for this overlay's DWM backdrop.
    const bool regionCleared = !overlay_ || overlay_->ClearContentRegion();
    // 最终落位后重申圆角偏好：上面的 SetWindowPos 尺寸变更与 SetWindowRgn(NULL)
    // 区域清理都可能让 DWM 重新评估窗口的圆角资格（regioned 窗口会被按方角处理），
    // 属性值虽持久，裁角决策却随帧状态变化。写入幂等，逐 show 重申兜底。
    if (overlay_ && windowModel_ == MenuWindowModel::ContentSized) {
        overlay_->SetCornerPreferenceOverride(PopupWindow::kCornerRound);
    }
    return regionCleared;
}

bool MenuOverlayHost::EnsureSubmenuCreated() {
    if (submenuOverlay_ && submenuHwnd_ && IsWindow(submenuHwnd_)) return true;

    submenuOverlay_ = std::make_unique<MenuOverlayWindow>();
    submenuOverlay_->SetReadyHtml(BuildMenuOverlayHtml());
    submenuOverlay_->SetWebViewReadyCallback([]() {
        MenuOverlayHost::GetInstance().OnSubmenuWebViewReady();
    });
    PopupWindow::CreateParams params;
    params.url = "";
    params.width = 16;
    params.height = 16;
    params.x = -32000;
    params.y = -32000;
    params.title = "MenuOverlaySubmenu";
    params.resizable = false;
    params.frame = false;
    params.transparent = true;
    params.alwaysOnTop = true;
    params.showInTaskbar = false;
    params.beforeClose = false;
    // 同根窗：豁免默认最小尺寸，子菜单面板通常远小于 200×150 DIP。
    params.minWidth = 1;
    params.minHeight = 1;
    params.hasBehavior = true;
    params.behavior = {
        {"noActivate", false},
        {"owner", "none"},
        {"showInTaskbar", false},
        {"showInAltTab", false},
        {"keepVisibleOnShowDesktop", true}
    };
    params.hasBackdropPolicy = true;
    params.backdropPolicy = {
        {"activeEffect", currentBackdrop_},
        {"inactiveEffect", currentBackdrop_},
        {"darkMode", currentBackdropDarkMode_}
    };
    submenuHwnd_ = submenuOverlay_->Create(params, "__menu_overlay_submenu__", core_api::get_main_window());
    if (!submenuHwnd_) {
        submenuOverlay_.reset();
        return false;
    }
    submenuOverlay_->SetSuppressLifecycleBroadcast(true);
    submenuOverlay_->SetMenuDismissCallback([](const std::string& reason, HWND other) {
        MenuOverlayHost::GetInstance().OnSubmenuDismissRequested(reason, other);
    });
    // 子菜单窗恒为内容尺寸面板，半径与根菜单同为 ROUND（Win11 菜单标准 8 DIP）。
    submenuOverlay_->SetCornerPreferenceOverride(PopupWindow::kCornerRound);
    ShowWindow(submenuHwnd_, SW_HIDE);
    return true;
}

bool MenuOverlayHost::ShowSubmenuWindow(const menu_overlay_geometry::Rect& virtualRect,
                                        const std::string& parentToken) {
    // 握手取证：子菜单窗可见化的最终一步（仅 ready 校验通过后到达）。
    {
        std::ostringstream oss;
        oss << "[MenuOverlayHost] ShowSubmenuWindow rect=(" << virtualRect.x << ","
            << virtualRect.y << "," << virtualRect.w << "," << virtualRect.h << ")"
            << " token=" << parentToken.substr(0, 8)
            << " webviewReady="
            << ((submenuOverlay_ && submenuOverlay_->IsWebViewReady()) ? 1 : 0);
        WindowChromeTrace::EmitAuxiliaryLine(oss.str());
    }
    if (!submenuOverlay_ || !submenuHwnd_ || !IsWindow(submenuHwnd_) ||
        !submenuOverlay_->IsWebViewReady() || parentToken.empty()) {
        return false;
    }
    if (virtualRect.w <= 0 || virtualRect.h <= 0) return false;
    openSubmenuVirtualRect_ = virtualRect;
    openSubmenuParentToken_ = parentToken;
    // Position and resize while hidden. The caller only reaches this point
    // after the submenu DOM has acknowledged its current token-scoped items.
    // Thus the first DWM-composited visible frame already contains the panel.
    if (!SetWindowPos(submenuHwnd_, HWND_TOPMOST,
                      contentVirtualOrigin_.x + virtualRect.x,
                      contentVirtualOrigin_.y + virtualRect.y,
                      virtualRect.w, virtualRect.h, SWP_NOACTIVATE)) {
        return false;
    }
    if (!submenuOverlay_->ClearContentRegion()) return false;
    // 落位/清区域后重申（与根窗同理：区域操作会让 DWM 重估裁角资格）。
    submenuOverlay_->SetCornerPreferenceOverride(PopupWindow::kCornerRound);
    std::string backdropError;
    submenuOverlay_->UpdateBackdropPolicy(
        json{{"activeEffect", currentBackdrop_}, {"inactiveEffect", currentBackdrop_},
             {"darkMode", currentBackdropDarkMode_}}, backdropError);
    SyncWebViewToClient(submenuOverlay_.get(), submenuHwnd_);
    openingSubmenu_ = true;
    activationHandoff_ = true;  // root→submenu 内部交接：root 的 NCACTIVATE(FALSE) 不降观感
    ShowWindow(submenuHwnd_, SW_SHOW);
    SetForegroundWindow(submenuHwnd_);
    activationHandoff_ = false;
    openingSubmenu_ = false;
    SetWindowPos(submenuHwnd_, HWND_TOPMOST, 0, 0, 0, 0,
                 SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
    // 池化复用空白修复：SW_SHOW 之后必须再同步一次 WebView surface。
    // Visual Hosting 下，隐藏窗口期间的 Resize/帧提交可能被 Chromium 挂起，
    // 显示后渲染器无 DOM 变化则永远不出新帧（用户看到 acrylic 裸窗）。
    // 根窗池化 Show() 与冷启动 startup reveal（RefreshStartupRevealSurface）
    // 均为"显示后同步"，仅本路径缺失——冷启动子菜单恰好被 startup reveal
    // 补了显示后同步，故"第一次正常、池化复用空白"（2026-08-13 取证：
    // 空白时握手全绿、DOM/opacity 均正常，唯窗口无内容帧）。
    SyncWebViewToClient(submenuOverlay_.get(), submenuHwnd_);
    if (auto* wv = submenuOverlay_->GetWebView()) {
        if (auto* ctrl = wv->GetController()) {
            ctrl->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);
        }
    }
    if (submenuOverlay_->GetBridge()) {
        submenuOverlay_->GetBridge()->EmitEvent("menu:__submenuVisible", {{"menuId", currentMenuId_}});
    }
    return true;
}

void MenuOverlayHost::HideSubmenuWindow(bool restoreRootFocus, bool notifyRoot, bool clearState) {
    // 握手取证：隐藏路径的三参语义 + 隐藏前窗口可见性（区分真隐藏与空操作）。
    {
        std::ostringstream oss;
        oss << "[MenuOverlayHost] HideSubmenuWindow restoreFocus=" << (restoreRootFocus ? 1 : 0)
            << " notifyRoot=" << (notifyRoot ? 1 : 0)
            << " clearState=" << (clearState ? 1 : 0)
            << " wasVisible="
            << ((submenuHwnd_ && IsWindow(submenuHwnd_) && IsWindowVisible(submenuHwnd_)) ? 1 : 0)
            << " openToken=" << openSubmenuParentToken_.substr(0, 8);
        WindowChromeTrace::EmitAuxiliaryLine(oss.str());
    }
    if (clearState) {
        openSubmenuVirtualRect_.reset();
        openSubmenuParentToken_.clear();
        pendingSubmenuPanelSequence_.reset();
    }
    if (!submenuHwnd_ || !IsWindow(submenuHwnd_)) return;
    suppressSubmenuDismiss_ = true;
    activationHandoff_ = true;  // submenu→root 内部交接：submenu 的失活不降观感/不误 blur
    ShowWindow(submenuHwnd_, SW_HIDE);
    // 子菜单是独立 MenuOverlayWindow（: public PopupWindow，自带 WebView），收口同根窗。
    // 置于 suppressSubmenuDismiss_/activationHandoff_ 窗口内，与随后的焦点归还同批完成。
    CollapseWebViewSurface(submenuOverlay_.get(), submenuHwnd_);
    if (restoreRootFocus && visible_ && overlayHwnd_ && IsWindow(overlayHwnd_)) {
        SetForegroundWindow(overlayHwnd_);
        if (overlay_ && overlay_->GetWebView() && overlay_->GetWebView()->GetController()) {
            overlay_->GetWebView()->GetController()->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);
        }
    }
    activationHandoff_ = false;
    suppressSubmenuDismiss_ = false;
    if (notifyRoot && overlay_ && overlay_->IsWebViewReady() && overlay_->GetBridge()) {
        overlay_->GetBridge()->EmitEvent("menu:__submenuClosed", {{"menuId", currentMenuId_}});
    }
}

void MenuOverlayHost::OnSubmenuWebViewReady() {
    // The child page's bootstrap pull renders the current token-scoped state
    // and acknowledges `menu.__submenuPanel` with `ready:true`; do not expose
    // a backdrop before then.
}

void MenuOverlayHost::OnRootDismissRequested(const std::string& reason, HWND other) {
    // Activating the independently hosted submenu deactivates the root HWND.
    // That hand-off is internal, not an outside click and must not close either
    // panel before the submenu receives its first input.
    // 内部交接判定只信失活消息的对端窗口 other（GA_ROOT 归一，覆盖 Chromium
    // 内部子 HWND）：对端属于菜单面 = root↔submenu 交接 → 不关。禁止改用
    // GetForegroundWindow()——失活消息的同步处理期间同进程激活转移尚未完成，
    // 它仍返回菜单窗自己，会把"点击宿主窗口"的真实失焦全部误判成内部腾挪
    //（2026-08-13 取证实锤：三次外点击 fg=overlay 自身而 other=主窗，菜单常驻）。
    // other 为空（WM_ACTIVATEAPP 跨进程失活 / lParam=NULL）或外部窗口 → 关闭。
    const bool internalHandoff = reason == "blur" && IsMenuSurfaceWindow(other);
    const bool swallow = openingSubmenu_ || internalHandoff;
    // dismiss 链取证。fg 仅作对照观测，不参与判定。
    {
        const HWND fg = GetForegroundWindow();
        std::ostringstream oss;
        oss << "[MenuOverlayHost] RootDismissReq reason=" << reason
            << " other=0x" << pfc::format_hex((size_t)other)
            << " fg=0x" << pfc::format_hex((size_t)fg)
            << " overlay=0x" << pfc::format_hex((size_t)overlayHwnd_)
            << " submenu=0x" << pfc::format_hex((size_t)submenuHwnd_)
            << " openingSub=" << (openingSubmenu_ ? 1 : 0)
            << " visible=" << (visible_ ? 1 : 0)
            << " closing=" << (closing_ ? 1 : 0)
            << " decision=" << (swallow ? "swallow" : "hide");
        WindowChromeTrace::EmitAuxiliaryLine(oss.str());
    }
    if (swallow) {
        return;
    }
    Hide(reason);
}

void MenuOverlayHost::OnSubmenuDismissRequested(const std::string& reason, HWND other) {
    if (suppressSubmenuDismiss_ || !visible_ || closing_) return;
    // escape = 键盘收子菜单回根面板；blur 且对端属于菜单面 = root↔submenu 内部
    // 交接（第一道 ShouldHoldOwnerActivation 已 hold 大部分，此为纵深防御）→
    // 仅收子菜单。其余（对端为外部窗口 / 跨进程失活的 nullptr）= 真实失焦 →
    // 整菜单关闭。禁止改用 GetForegroundWindow() 判定（同上：外点击宿主时它仍
    // 返回子菜单窗自己，误走 collapse 且 restoreRootFocus 会反抢用户点击目标的
    // 前台，菜单常驻——2026-08-13 取证实锤）。
    const bool collapse = reason == "escape" ||
                          (reason == "blur" && IsMenuSurfaceWindow(other));
    {
        const HWND fg = GetForegroundWindow();
        std::ostringstream oss;
        oss << "[MenuOverlayHost] SubDismissReq reason=" << reason
            << " other=0x" << pfc::format_hex((size_t)other)
            << " fg=0x" << pfc::format_hex((size_t)fg)
            << " overlay=0x" << pfc::format_hex((size_t)overlayHwnd_)
            << " submenu=0x" << pfc::format_hex((size_t)submenuHwnd_)
            << " visible=" << (visible_ ? 1 : 0)
            << " closing=" << (closing_ ? 1 : 0)
            << " decision=" << (collapse ? "collapse" : "hide");
        WindowChromeTrace::EmitAuxiliaryLine(oss.str());
    }
    if (collapse) {
        HideSubmenuWindow(true, true);
        return;
    }
    Hide(reason);
}

void MenuOverlayHost::SyncWebViewToClient(MenuOverlayWindow* window, HWND hwnd) const {
    if (!window || !hwnd || !IsWindow(hwnd) || !window->IsWebViewReady()) return;
    if (auto* wv = window->GetWebView()) {
        RECT rc{};
        GetClientRect(hwnd, &rc);
        wv->SetVisible(true);
        wv->Resize(rc);
        if (auto* ctrl = wv->GetController()) ctrl->NotifyParentWindowPositionChanged();
    }
}

void MenuOverlayHost::CollapseWebViewSurface(MenuOverlayWindow* window, HWND hwnd) const {
    if (!window || !hwnd || !IsWindow(hwnd) || !window->IsWebViewReady()) return;
    if (auto* wv = window->GetWebView()) {
        // 用 SetBoundsVisible(false)（put_Bounds({0,0,0,0}) + DComp 裁剪归零），
        // 不用 SetVisible(false)：overlay 是池化复用的，put_IsVisible(FALSE) 会让页面
        // 进 visibilityState=hidden 并节流定时器，下次开菜单可能首帧空白/延迟
        //（"池化复用空白"已在 ShowSubmenuWindow 处踩过一次）。菜单场景要的是
        // 命中区与出帧一起归零、页面保持热态，正是 SetBoundsVisible 的语义。
        wv->SetBoundsVisible(false);
    }
}

json MenuOverlayHost::BuildRootGeometryJson(const menu_overlay_geometry::Placement& placement) const {
    return {
        {"viewportW", placement.rootSlotW},
        {"viewportH", placement.rootVisibleH},
        {"rootSlotW", placement.rootSlotW},
        {"subSlotW", placement.subSlotW},
        {"rootTop", 0},
        {"virtualViewportH", placement.viewportH},
        {"virtualRootTop", placement.rootTop}
    };
}

std::optional<json> MenuOverlayHost::FindSubmenuItems(const std::string& parentToken) const {
    if (parentToken.empty()) return std::nullopt;
    const auto findInItems = [&parentToken](const json& items) -> std::optional<json> {
        if (!items.is_array()) return std::nullopt;
        for (const auto& item : items) {
            if (item.is_object() && item.value("_token", std::string()) == parentToken &&
                item.contains("submenu") && item["submenu"].is_array() && !item["submenu"].empty()) {
                return item["submenu"];
            }
        }
        return std::nullopt;
    };
    if (overlayModel_ == MenuOverlayModel::TrayZones) {
        for (const auto& zone : currentZones_) {
            if (zone.is_object() && zone.contains("items")) {
                if (auto items = findInItems(zone["items"])) return items;
            }
        }
        return std::nullopt;
    }
    return findInItems(currentItems_);
}

void MenuOverlayHost::ArmWatchdog() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        SetTimer(overlayHwnd_, kWatchdogTimerId, kWatchdogTimeoutMs, &MenuOverlayHost::WatchdogTimerProc);
    }
}

void MenuOverlayHost::KillWatchdog() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        KillTimer(overlayHwnd_, kWatchdogTimerId);
    }
}

void CALLBACK MenuOverlayHost::WatchdogTimerProc(HWND /*hwnd*/, UINT /*msg*/, UINT_PTR idEvent, DWORD /*elapsed*/) {
    if (idEvent != kWatchdogTimerId) {
        return;
    }
    MenuOverlayHost::GetInstance().Hide("timeout");
}

void MenuOverlayHost::ArmMeasureTimer() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        SetTimer(overlayHwnd_, kMeasureTimerId, kMeasureTimeoutMs, &MenuOverlayHost::MeasureTimerProc);
    }
}

void MenuOverlayHost::KillMeasureTimer() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        KillTimer(overlayHwnd_, kMeasureTimerId);
    }
}

void CALLBACK MenuOverlayHost::MeasureTimerProc(HWND /*hwnd*/, UINT /*msg*/, UINT_PTR idEvent, DWORD /*elapsed*/) {
    if (idEvent != kMeasureTimerId) {
        return;
    }
    // ContentSized 测量回报兜底：超时未收 menu.__ready 即关闭，避免卡在临时尺寸。
    auto& self = MenuOverlayHost::GetInstance();
    if (self.measureGate_.IsAwaiting()) {
        self.Hide("measure_timeout");
    }
}

void MenuOverlayHost::ArmCloseTimer(int ms) {
    if (!overlayHwnd_ || !IsWindow(overlayHwnd_)) {
        return;
    }
    if (ms < 0) ms = 0;
    if (ms > kCloseAnimationMaxMs) ms = kCloseAnimationMaxMs;   // 防御性 clamp（解析层已 clamp 0..1000）
    SetTimer(overlayHwnd_, kCloseTimerId, static_cast<UINT>(ms), &MenuOverlayHost::CloseTimerProc);
}

void MenuOverlayHost::KillCloseTimer() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        KillTimer(overlayHwnd_, kCloseTimerId);
    }
}

void CALLBACK MenuOverlayHost::CloseTimerProc(HWND /*hwnd*/, UINT /*msg*/, UINT_PTR idEvent, DWORD /*elapsed*/) {
    if (idEvent != kCloseTimerId) {
        return;
    }
    // 退场动画收尾：退场时长到期后做与立即路径等价的同步收尾。reason 用进入 Closing 时记录的原始值。
    auto& self = MenuOverlayHost::GetInstance();
    if (self.closing_) {
        self.FinalizeHide(self.pendingCloseReason_);
    }
}